server:
  servlet:
    context-path: "/api"

app:
  users:
    user-name: user
    user-password: user
    admin-name: admin
    admin-password: admin

spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:hsqldb:hsql://localhost/db1
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbcDriver
  h2:
    console:
      enabled: true
  liquibase:
    clear-checksums: true
    change-log: classpath:db/changelog/db.changelog-master.xml
jwt:
  key: r6m4GNX6voKiPh5pfCaWkQoG8d1E756ioKiPh2pfCaWk59ioKiPh2h5pfCaWkQoG8d1E756io
  duration-min: 15